Updated instructions based on feedback portal
telerik/justmock-docs pull request #51
Opened 2020-10-02 08:41 UTC by ogardy

Updated the instruction to reflect VS 2019 approach.
Feedback comment from 10/07/2020 14:47 Complete

2020-10-02 08:46 UTC, ivo-stoilov approved these changes
:shipit:

2020-10-02 09:15 UTC, yordan-mitev commented on getting-started/using-telerik-justmock-in-your-test-project.md
> +1. Select the Test Project template or search for it by typing "JustMock test". After that select the Test Project template and click OK.
```suggestion
1. Select the desired **JustMock Test Project** template from the menu and click OK. 
```
The first sentence instructs the reader to select the Test Project template. The second sentence duplicates the same instructions and asks the reader to  select the Test Project template again.
We can omit the template search instruction, I am not sure if the add more value.

2020-10-05 11:35 UTC, mihail-vladov requested changes
@ogardy Could you address the comment? Thanks.

2020-10-05 11:35 UTC, mihail-vladov commented on getting-started/using-telerik-justmock-in-your-test-project.md
> +	![JustMock Test Project Template](images/ProjectTemplate1.png)
Please replace the image or remove the old and add a new one with a different name if required. And please try to name the images according to their usage.

2020-10-05 12:58 UTC, mihail-vladov approved these changes

2020-10-05 12:59 UTC, merged